#Use root/example as user/password credentials 
version: '3.1'

services:
  web:
    build: .
    ports:
      - "9090:9090"
    links:
      - db
  db:
    image: mysql:latest
    ports:
      - "33060:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: BountyMail
      MYSQL_USER: test
      MYSQL_PASSWORD: 123

    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
