#!/bin/bash
function usage(){
	echo  "Usage: "
	echo  "${1} script is in testing phase "
	echo  ""
}

function help(){
	echo "******HELP*******"
	echo "Yeah good luck"
}


#### MAIN
SCRIPTNAME=`basename $0`
if [ ${#} -lt 1 ]; then 
	usage $SCRIPTNAME
fi 

args=`getopt bhs ${*}`
set --$args

alias DEST=`cd flask-BountyMail`

while :; do
	case "${1}" in 
		-h)#Help Menu
			help ${SCRIPTNAME}
			exit 1;
			shift
			;;
		-s)#starting flask env if env already built
			FLASK_APP=bounty flask init && FLASK_APP=bounty flask run
			shift
			;;

		-b)#actually instailing the dependencies
		        sudo apt update && sudo apt install -y python3 python3-flask python3-virtualenv
			exit 1;
			shift
			;;
		--)
			shift;break
			;;
	esac
done
